export type ScrumTopic =
  | "scrumGuide"
  | "scrumRoles"
  | "scrumEvents"
  | "scrumArtifacts";

export type ScrumQuestion = {
  id: number;
  topic: ScrumTopic;
  prompt: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
};

export const scrumQuestions: ScrumQuestion[] = [
  {
    id: 1,
    topic: "scrumRoles",
    prompt: "Who decides which stories to prioritize?",
    options: [
      "Scrum Master",
      "Investors",
      "Team Members",
      "Case Manager",
      "Product Owner",
    ],
    correctAnswer: "Product Owner",
    explanation: "The Product Owner is responsible for prioritizing stories in the backlog",
  },
  {
    id: 2,
    topic: "scrumEvents",
    prompt: "When should the team have retrospective meetings?",
    options: [
      "Every evening via conference call",
      "Three times per week during lunch",
      "At the end of each sprint",
      "Every morning before the workday starts",
      "Once before the release",
    ],
    correctAnswer: "At the end of each sprint",
    explanation: "Retrospectives are held at the end of each sprint to reflect on performance and identify improvements",
  },
  {
    id: 3,
    topic: "scrumGuide",
    prompt: "What is the benefit of the waterfall model?",
    options: [
      "Improves ROI",
      "Increases visibility",
      "Makes it easier to find defects earlier",
      "Accommodates changes easily",
      "It is a very disciplined approach",
    ],
    correctAnswer: "It is a very disciplined approach",
    explanation: "The waterfall model follows a structured, sequential process, making it a disciplined and predictable approach",
  },
  {
    id: 4,
    topic: "scrumEvents",
    prompt: "Which of the following is not a scrum ceremony?",
    options: [
      "Daily scrum meeting",
      "Sprint retrospective",
      "Sprint review",
      "Sprint backlog",
      "Sprint planning",
    ],
    correctAnswer: "Sprint backlog",
    explanation: "The sprint backlog is an artifact, not a ceremony, while the others are Scrum events",
  },
  {
    id: 5,
    topic: "scrumArtifacts",
    prompt: "Which of the following help indicate what is left to do, what is in progress, and what is done?",
    options: [
      "The sprint backlog",
      "Burn charts",
      "Sprint retrospective",
      "Information radiators",
      "TPS reports",
    ],
    correctAnswer: "Information radiators",
    explanation: "Information radiators visually display work status, showing what is to do, in progress, and done",
  },
  {
    id: 6,
    topic: "scrumArtifacts",
    prompt: "Which of the following is not a scrum artifact?",
    options: [
      "Information radiator",
      "Bug history",
      "Product backlog",
      "Definition of done",
      "Sprint backlog",
    ],
    correctAnswer: "Bug history",
    explanation: "Bug history is not a Scrum artifact, while product backlog, sprint backlog, and definition of done are official artifacts",
  },
  {
    id: 7,
    topic: "scrumGuide",
    prompt: "Which of the following is not in the micro charter?",
    options: [
      "Mission statement",
      "Ethical values",
      "Trade-offs",
      "Elevator pitch",
      "Risks",
    ],
    correctAnswer: "Ethical values",
    explanation: "Ethical values are not part of a micro charter, which focuses on goals, scope, and trade-offs for the project",
  },
  {
    id: 8,
    topic: "scrumArtifacts",
    prompt: "What does a burn down chart predict?",
    options: [
      "A rank of most productive team members from best to worst",
      "A list of features to be implemented in order of priority",
      "Work left to be done over time",
      "Amount of budget spent over time",
      "A list of use cases in order of priority",
    ],
    correctAnswer: "Work left to be done over time",
    explanation: "A burndown chart shows how much work remains over time, helping track progress toward completing a sprint",
  },
  {
    id: 9,
    topic: "scrumRoles",
    prompt: "What are the three scrum roles?",
    options: [
      "Product owner, scrum master, team member",
      "Product owner, scrum master, servant",
      "Product owner, manager, developer",
      "CEO, scrum master, team member",
      "CEO, manager, developer",
    ],
    correctAnswer: "Product owner, scrum master, team member",
    explanation: "Scrum consists of three roles: Product Owner, Scrum Master, and the development team",
  },
  {
    id: 10,
    topic: "scrumGuide",
    prompt: "Which are bigger: tasks or stories?",
    options: [
      "You cannot tell because they are not time dependent",
      "It depends on the development status of the project",
      "Both are the same size",
      "Tasks",
      "Stories",
    ],
    correctAnswer: "Stories",
    explanation: "Stories are larger units of work that are typically broken down into smaller tasks",
  },
  {
    id: 11,
    topic: "scrumRoles",
    prompt: "What does the product owner do?",
    options: [
      "Controls the priority of backlog items",
      "Front-end programming",
      "Assigns tasks to the individual team members",
      "CSS and HTML programming",
      "Manages the publication of team reports",
    ],
    correctAnswer: "Controls the priority of backlog items",
    explanation: "The Product Owner is responsible for prioritizing backlog items to maximize product value",
  },
  {
    id: 12,
    topic: "scrumArtifacts",
    prompt: "What is a sprint backlog?",
    options: [
      "What features the team wants to release",
      "What each team member brings to a sprint",
      "A wooden object you run on",
      "What the team needs to do for each sprint",
      "What features will be released in the product",
    ],
    correctAnswer: "What the team needs to do for each sprint",
    explanation: "The sprint backlog is the set of work the team commits to complete during a sprint",
  },
  {
    id: 13,
    topic: "scrumGuide",
    prompt: "Which of the following is not a stage included in the waterfall method?",
    options: [
      "Coding",
      "Periodic meetings",
      "Design",
      "Testing",
      "Requirement gathering",
    ],
    correctAnswer: "Periodic meetings",
    explanation: "Periodic meetings are not a defined stage in waterfall, which follows phases like requirements, design, coding, and testing",
  },
  {
    id: 14,
    topic: "scrumRoles",
    prompt: "Which is not a responsibility of the product owner?",
    options: [
      "Helps set the direction of the product",
      "Judges the work done",
      "Captures product vision",
      "Writes customer-centric items",
      "Creates initial product backlog",
    ],
    correctAnswer: "Judges the work done",
    explanation: "The Product Owner defines and prioritizes work, but the team is responsible for evaluating and delivering it",
  },
  {
    id: 15,
    topic: "scrumGuide",
    prompt: "What is not a characteristic of agile approaches?",
    options: [
      "Big design up front",
      "Small iterative cycles",
      "Fail-early lifecycle",
      "Provide early milestones",
      "Adaptive, empirical process",
    ],
    correctAnswer: "Big design up front",
    explanation: "Big design up front is not agile because agile focuses on iterative development and adapting over time",
  },
  {
    id: 16,
    topic: "scrumGuide",
    prompt: "If a team's velocity is good, and they seem to be getting all work done by deadlines, what is an appropriate action?",
    options: [
      "Decrease the number of points per sprint",
      "Increase the number of points per sprint to get more work done",
      "Assign harder stories in the next sprint",
      "Decrease the size of the team",
      "Leave the number of points per sprint as is",
    ],
    correctAnswer: "Leave the number of points per sprint as is",
    explanation: "If the team is consistently meeting goals, the current workload is well calibrated and should not be changed",
  },
  {
    id: 17,
    topic: "scrumGuide",
    prompt: "Where does the name scrum come from?",
    options: [
      "It's an acronym for Software Coding and Reading Uniform Management",
      "From the action of scrubbing, figuratively polishing the inefficiency of software development",
      "It's a rugby term",
      "It's an acronym for Simple Code Refactoring Unique Methodology",
      "Its creator liked the way it sounded",
    ],
    correctAnswer: "It's a rugby term",
    explanation: "The term scrum comes from rugby, where a scrum represents a team working closely together to move the ball forward",
  },
  {
    id: 18,
    topic: "scrumGuide",
    prompt: "Which of the following is not a feature of agile methodologies?",
    options: [
      "Perfect the requirements before you code",
      "Build cross-functional teams",
      "Deliver products early and often",
      "Test as you go",
      "Document as you go",
    ],
    correctAnswer: "Perfect the requirements before you code",
    explanation: "Agile avoids fully defining perfect requirements upfront and instead adapts requirements throughout development",
  },
  {
    id: 19,
    topic: "scrumGuide",
    prompt: "Which of these are three common ways to estimate tasks for sprint planning?",
    options: [
      "Task wages, task meetings, task complexity",
      "Task hours, task points, task count",
      "Task drivers, task risks, task profit",
      "Task break-even, task weeks, task subtasks",
      "Task score, task variance, task years",
    ],
    correctAnswer: "Task hours, task points, task count",
    explanation: "Teams commonly estimate using time (hours), relative size (points), or number of tasks to plan sprint workload",
  },
  {
    id: 20,
    topic: "scrumRoles",
    prompt: "Which is not a role of the scrum master?",
    options: [
      "Team coach",
      "Helps understand the use of the artifacts of scrum",
      "Facilitates scrum meetings",
      "Team boss",
      "Removes impediments for the team",
    ],
    correctAnswer: "Team boss",
    explanation: "The Scrum Master is not a boss but a servant-leader who supports and facilitates the team",
  },
  {
    id: 21,
    topic: "scrumEvents",
    prompt: "Which are the three formal feedback cycles?",
    options: [
      "Paper prototyping, Q+A, story mapping",
      "User stories, daily scrum, sprint review",
      "Daily scrum, sprint review, retrospective",
      "Refactoring, testing, retrospective",
      "Q+A, testing, burn charts",
    ],
    correctAnswer: "Daily scrum, sprint review, retrospective",
    explanation: "The daily scrum, sprint review, and retrospective are Scrum’s formal feedback loops for continuous inspection and improvement",
  },
  {
    id: 22,
    topic: "scrumGuide",
    prompt: "What is the first step of the waterfall method?",
    options: [
      "Gathering a team",
      "Designing the project",
      "Setting the stage",
      "Deciding what to do",
      "Requirements gathering",
    ],
    correctAnswer: "Requirements gathering",
    explanation: "The waterfall process begins with requirements gathering to define what the system needs to do before any design or development starts",
  },
  {
    id: 23,
    topic: "scrumGuide",
    prompt: "BDUF stands for what?",
    options: [
      "Best Decision Unit Features",
      "Big Design Unit File",
      "Big Design Up Front",
      "Biosoftware Development Utility Fact",
      "Bold Development Up Front",
    ],
    correctAnswer: "Big Design Up Front",
    explanation: "BDUF means designing the entire system upfront before development, which contrasts with Agile’s iterative approach",
  },
  {
    id: 24,
    topic: "scrumGuide",
    prompt: "What do all agile methods have in common?",
    options: [
      "Return methodologies",
      "Cross-functional methodologies",
      "Well-defined methodologies",
      "Iterative methodologies",
      "Bi-lateral methodologies",
    ],
    correctAnswer: "Iterative methodologies",
    explanation: "Agile methods are iterative, meaning work is done in repeated cycles with continuous feedback and improvement",
  },
  {
    id: 25,
    topic: "scrumEvents",
    prompt: "Why do scrum meetings happen standing up?",
    options: [
      "To wake everyone up",
      "To encourage brevity",
      "To burn calories",
      "So it is uncomfortable for all involved",
      "So it can be done anywhere, also in the corridor",
    ],
    correctAnswer: "To encourage brevity",
    explanation: "Standing encourages meetings to stay short and focused",
  },
  {
    id: 26,
    topic: "scrumGuide",
    prompt: "What is considered a good scrum team size?",
    options: [
      "7 +- 2",
      "3 +- 1",
      "15 +- 10",
      "9 +- 4",
      "5 +- 3",
    ],
    correctAnswer: "7 +- 2",
    explanation: "A Scrum team is typically around 7 ± 2 members to stay small enough for collaboration but large enough to get work done",
  },
  {
    id: 27,
    topic: "scrumArtifacts",
    prompt: "Which is false about a story map?",
    options: [
      "It is always a replacement for a product backlog",
      "It indicates the priority of stories",
      "A story map was used to help write the book",
      "It helps the team understand how stories fit together",
      "It is two-dimensional",
    ],
    correctAnswer: "It is always a replacement for a product backlog",
    explanation: "A story map complements the product backlog but does not replace it",
  },
  {
    id: 28,
    topic: "scrumGuide",
    prompt: "In TDD pair programming, what is the only move when in the red state?",
    options: [
      "Perform a refactoring",
      "Write code to make the failing tests pass",
      "Write new failing tests",
      "Redesign code from scratch",
      "Write new passing tests",
    ],
    correctAnswer: "Write code to make the failing tests pass",
    explanation: "In TDD, the red state means tests are failing, so the next step is to write code to make them pass",
  },
  {
    id: 29,
    topic: "scrumRoles",
    prompt: "Which of these is a role in a scrum team?",
    options: [
      "Scrum apprentice",
      "Scrum analyzer",
      "Product overviewer",
      "Scrum master",
      "Product marketer",
    ],
    correctAnswer: "Scrum master",
    explanation: "Scrum Master is one of the three defined roles in a Scrum team",
  },
  {
    id: 30,
    topic: "scrumRoles",
    prompt: "The scrum master roles include all the following except what?",
    options: [
      "Scrum expert and advisor",
      "Coach",
      "Prioritizes stories",
      "Impediment bulldozer",
      "Facilitator",
    ],
    correctAnswer: "Prioritizes stories",
    explanation: "The Scrum Master does not prioritize stories; that responsibility belongs to the Product Owner",
  },
  {
    id: 31,
    topic: "scrumEvents",
    prompt: "How long should sprints be?",
    options: [
      "1-4 months",
      "1-4 tasks",
      "1-4 days",
      "1-4 years",
      "1-4 weeks",
    ],
    correctAnswer: "1-4 weeks",
    explanation: "Sprints are time-boxed to 1–4 weeks to keep work focused and allow for regular feedback and iteration",
  },
  {
    id: 32,
    topic: "scrumArtifacts",
    prompt: "The product backlog includes a list of what?",
    options: [
      "Preferred coding languages",
      "Features",
      "Available resources",
      "Client names",
      "Available funds",
    ],
    correctAnswer: "Features",
    explanation: "The product backlog is a prioritized list of features and functionality to be built",
  },
  {
    id: 33,
    topic: "scrumEvents",
    prompt: "The daily scrum is also called what?",
    options: [
      "Stand-up meeting",
      "Brief meeting",
      "Daily brainstorm",
      "Scrummy meeting",
      "Decision planning meeting",
    ],
    correctAnswer: "Stand-up meeting",
    explanation: "The daily scrum is commonly called a stand-up meeting because it’s a short, quick team check-in",
  },
  {
    id: 34,
    topic: "scrumGuide",
    prompt: "What is refactoring?",
    options: [
      "Altering the internal structure of code without changing its external behavior",
      "Dividing a team up into smaller teams, or combining teams together",
      "A procedure that is done at the end of every sprint",
      "Replacing module with several smaller sub-modules",
      "Changing the priority of the features to be implemented in the product backlog",
    ],
    correctAnswer: "Altering the internal structure of code without changing its external behavior",
    explanation: "Refactoring improves the internal structure of code without changing what the code does externally",
  },
  {
    id: 35,
    topic: "scrumRoles",
    prompt: "Who is responsible for the product backlog?",
    options: [
      "Scrum master",
      "Project manager",
      "Product owner",
      "Team member",
      "Sprint backlogger",
    ],
    correctAnswer: "Product owner",
    explanation: "The product owner is responsible for managing and prioritizing the product backlog",
  },
  {
    id: 36,
    topic: "scrumGuide",
    prompt: "What elements are in the iron triangle of a project?",
    options: [
      "Pace, integration, documentation",
      "Scope, deadline, knowledge",
      "Cost, documentation, integration",
      "Documentation, user requirements, API",
      "Speed, scope, cost",
    ],
    correctAnswer: "Speed, scope, cost",
    explanation: "The iron triangle consists of speed (time), scope, and cost, which must be balanced in any project",
  },
  {
    id: 37,
    topic: "scrumGuide",
    prompt: "Scrum indicates an iterative approach to getting work done through what?",
    options: [
      "Leaps",
      "Loops",
      "Jumps",
      "Swims",
      "Sprints",
    ],
    correctAnswer: "Sprints",
    explanation: "Scrum uses sprints, which are short, repeated cycles of work that allow for continuous iteration and improvement",
  },
  {
    id: 38,
    topic: "scrumEvents",
    prompt: "What shouldn't the daily scrum be?",
    options: [
      "Daily",
      "Optional",
      "Pointed",
      "Brief",
      "Small",
    ],
    correctAnswer: "Optional",
    explanation: "The daily scrum is a required event in Scrum and should not be optional",
  },
  {
    id: 39,
    topic: "scrumArtifacts",
    prompt: "The sprint backlog is what?",
    options: [
      "A review of what has been accomplished in previous sprints",
      "The team's to-do list for the sprint",
      "The list of all features to be included in the product",
      "The final sprint",
      "A large piece of wood that one wears while performing sprints",
    ],
    correctAnswer: "The team's to-do list for the sprint",
    explanation: "The sprint backlog is the set of tasks the team plans to complete during the current sprint",
  },
  {
    id: 40,
    topic: "scrumGuide",
    prompt: "When practicing agile methodologies, you will do all of the following except what?",
    options: [
      "Document as you go",
      "Design the full product first before all other stages",
      "Test as you go",
      "Build cross-functional teams",
      "Deliver product early and often",
    ],
    correctAnswer: "Design the full product first before all other stages",
    explanation: "Agile avoids fully designing the entire product upfront and instead emphasizes iterative development and continuous improvement",
  },
  {
    id: 41,
    topic: "scrumGuide",
    prompt: "A backlog item is often to referred to as a what?",
    options: [
      "Quest",
      "Task",
      "Fable",
      "Chunk",
      "Story",
    ],
    correctAnswer: "Story",
    explanation: "Backlog items are commonly called user stories because they describe features from the user’s perspective",
  },
  {
    id: 42,
    topic: "scrumGuide",
    prompt: "What is the correct order of the waterfall method?",
    options: [
      "Requirements, implementation, design, verification, maintenance",
      "Requirements, implementation, design, maintenance, verification",
      "Verification, design, requirements, maintenance, implementation",
      "Maintenance, verification, implementation, design, requirements",
      "Requirements, design, implementation, verification, maintenance",
    ],
    correctAnswer: "Requirements, design, implementation, verification, maintenance",
    explanation: "The waterfall model follows a linear sequence starting with requirements, then design, implementation, verification, and finally maintenance",
  },
  {
    id: 43,
    topic: "scrumGuide",
    prompt: "What is the primary measure of progress in scrum?",
    options: [
      "ROI",
      "Number of meetings completed",
      "Accomplishment of team members' goals",
      "Completion of points in a contract",
      "Working software",
    ],
    correctAnswer: "Working software",
    explanation: "Working software is the primary measure of progress because it represents tangible, usable value delivered to users",
  },
  {
    id: 44,
    topic: "scrumRoles",
    prompt: "How many scrum roles are there in a team?",
    options: [
      "4",
      "3",
      "6",
      "2",
      "5",
    ],
    correctAnswer: "3",
    explanation: "Scrum defines three roles: Product Owner, Scrum Master, and Developer",
  },
  {
    id: 45,
    topic: "scrumEvents",
    prompt: "What is not shared at the daily scrum?",
    options: [
      "What I plan to add for the next 3 scrums",
      "Quick points of development team members",
      "What I expect to accomplish by the next daily scrum",
      "What I accomplished since last daily scrum",
      "What obstacles are slowing me down",
    ],
    correctAnswer: "What I plan to add for the next 3 scrums",
    explanation: "The daily scrum focuses on short-term updates for the next day, not long-term plans across multiple future sprints",
  },
  {
    id: 46,
    topic: "scrumGuide",
    prompt: "Which set of numbers correlate with the rate as humans easily perceive differences, and are thus useful for story point estimations?",
    options: [
      "Imaginary",
      "Primes",
      "Fibonacci",
      "Geometric",
      "Natural",
    ],
    correctAnswer: "Fibonacci",
    explanation: "Fibonacci numbers grow with increasing gaps, making it easier for humans to distinguish relative effort between story sizes",
  },
  {
    id: 47,
    topic: "scrumArtifacts",
    prompt: "A task board is what type of radiator?",
    options: [
      "Importance",
      "Indispensable",
      "Inconsistency",
      "Information",
      "Inequality",
    ],
    correctAnswer: "Information",
    explanation: "A task board is an information radiator because it visually shares project status and progress with the team at a glance",
  },
  {
    id: 48,
    topic: "scrumEvents",
    prompt: "Which of the following is not part of the scrum development cycle?",
    options: [
      "Sprint retrospective",
      "Sprint planning",
      "Daily standup meeting",
      "Sprint refactoring",
      "Sprint review",
    ],
    correctAnswer: "Sprint refactoring",
    explanation: "Sprint refactoring is not an official Scrum event, while planning, daily standups, reviews, and retrospectives are defined parts of the cycle",
  },
  {
    id: 49,
    topic: "scrumGuide",
    prompt: "What is the point of estimating story size?",
    options: [
      "To decide which stories are worth adding to release backlog",
      "To provide predictability of schedule",
      "There is no point, assigning exact times is better",
      "To determine accountability for legal purpose",
      "To cut down planning so you can get to coding sooner",
    ],
    correctAnswer: "To provide predictability of schedule",
    explanation: "Estimating story size helps teams forecast how much work they can complete over time, making delivery timelines more predictable",
  },
  {
    id: 50,
    topic: "scrumGuide",
    prompt: "Which is not a way of pair programming?",
    options: [
      "Divide and conquer pairing",
      "Driver-navigator pairing",
      "Ping-pong pairing",
      "TDD pair programming",
      "Test driven development pair programming",
    ],
    correctAnswer: "Divide and conquer pairing",
    explanation: "Divide and conquer isn’t true pair programming because the developers split up work instead of working together on the same code at the same time",
  },
  {
  id: 51,
  topic: "scrumEvents",
    prompt: "On which days of the week should the ideal scrum team meet?",
    options: [
      "Monday, Wednesday, Friday",
      "Monday, Friday",
      "Monday, Tuesday, Wednesday",
      "Friday",
      "Every business day",
    ],
    correctAnswer: "Every business day",
    explanation: "The Scrum team meets every business day for the daily scrum (stand-up) to share progress, plan next steps, and identify any blockers.",
  },
  {
  id: 52,
  topic: "scrumGuide",
    prompt: "Which of these is NOT an element of the micro-charter?",
    options: [
      "Mission statement",
      "Fully developed code",
      "Milestones",
      "Trade-offs",
      "Elevator pitch",
    ],
    correctAnswer: "Fully developed code",
    explanation: "A micro-charter defines high-level project goals, scope, and direction, not the actual implementation or completed code.",
  },
  {
    id: 53,
    topic: "scrumRoles",
    prompt: "Which are the two required roles in a scrum team?",
    options: [
      "Scrum master, debugger",
      "Scrum master, product owner",
      "Software engineer, product owner",
      "Project manager, scrum master",
      "Software engineer, project manager",
    ],
    correctAnswer: "Scrum master, product owner",
    explanation: "Scrum requires a Product Owner and Scrum Master, along with developers, but the Scrum Master and Product Owner are the two explicitly defined leadership roles.",
  },
  {
    id: 54,
    topic: "scrumRoles",
    prompt: "Which of the following is NOT a scrum master role?",
    options: [
      "Scrum expert and advisor",
      "Coach",
      "Impediment bulldozer",
      "Facilitator",
      "Prioritizes stories",
    ],
    correctAnswer: "Prioritizes stories",
    explanation: "The Scrum Master facilitates and supports the team, but prioritizing stories is the responsibility of the Product Owner.",
  },
  {
    id: 55,
    topic: "scrumArtifacts",
    prompt: "What is the proper name for the cards that outline a project's details?",
    options: [
      "User Story",
      "Resource Card",
      "Program Card",
      "Planning Card",
      "Detail Card",
    ],
    correctAnswer: "User Story",
    explanation: "User stories describe features or requirements from the user's perspective and are typically written on cards for planning and tracking.",
  },
  {
    id: 56,
    topic: "scrumGuide",
    prompt: "In the Iron Triangle what does scope represent?",
    options: [
      "It involves how many stories will be included",
      "It refers to the time it will take to build and release the system",
      "It refers to the number of people working on the project and how they will be paid",
      "It refers to average stories completed per sprint",
      "It refers the amount of fake users one should build",
    ],
    correctAnswer: "It involves how many stories will be included",
    explanation: "Scope refers to the amount of work to be completed, typically represented by the number of features or user stories included in the project.",
  },
  {
    id: 57,
    topic: "scrumRoles",
    prompt: "Rank the Scrum Roles from Most to Least Authority",
    options: [
      "Team member, product owner, scrum master",
      "Scrum master, team member, product owner",
      "Product owner, scrum master, team member",
      "Scrum master, product owner, team member",
      "Each role has equal rank",
    ],
    correctAnswer: "Each role has equal rank",
    explanation: "Scrum emphasizes collaboration and self-organization, so all roles have equal standing rather than a strict hierarchy.",
  },
  {
    id: 58,
    topic: "scrumRoles",
    prompt: "Who is responsible for changing the priority of backlog items?",
    options: [
      "Scrum master",
      "Random team member",
      "Every team member",
      "Product owner",
      "Customer",
    ],
    correctAnswer: "Product owner",
    explanation: "The Product Owner is responsible for managing and prioritizing the product backlog to maximize value.",
  },
  {
    id: 59,
    topic: "scrumArtifacts",
    prompt: "Which is not a scrum artifact?",
    options: [
      "Burn charts",
      "Product backlog",
      "Information radiators",
      "Attendance chart",
      "Task board",
    ],
    correctAnswer: "Attendance chart",
    explanation: "Scrum artifacts include tools that track work and progress, while attendance charts are not related to managing or visualizing development work.",
  },
  {
    id: 60,
    topic: "scrumRoles",
    prompt: "A Scrum team consists of:",
    options: [
      "Product Developer, Scrum Master, and Team Members",
      "Product Master, Scrum Master, and Team Members",
      "Product Owner, Scrum Master, and Team Members",
      "Team Master, Scrum Master, Product Owner, and Team Members",
      "Team Members and Scrum Master",
    ],
    correctAnswer: "Product Owner, Scrum Master, and Team Members",
    explanation: "A Scrum team consists of a Product Owner, Scrum Master, and Developers (team members), each with distinct responsibilities.",
  },
  {
    id: 61,
    topic: "scrumGuide",
    prompt: "Which of the following is not a stage of the waterfall method",
    options: [
      "Requirements-gathering",
      "Design",
      "Coding",
      "Testing",
      "Marketing",
    ],
    correctAnswer: "Marketing",
    explanation: "The waterfall model includes stages like requirements, design, coding, and testing, but marketing is not part of the development lifecycle.",
  },
  {
    id: 62,
    topic: "scrumGuide",
    prompt: "Which of the following is NOT the characteristic of agile principles?",
    options: [
      "The highest priority is to satisfy the customer through early and continuous delivery of valuable software.",
      "Do not change requirements unless one absolutely has to.",
      "Deliver working software frequently.",
      "Working software is the primary measure of progress.",
      "Business people and developers must work together daily throughout the project.",
    ],
    correctAnswer: "Do not change requirements unless one absolutely has to.",
    explanation: "Agile embraces changing requirements, even late in development, to better meet customer needs.",
  },
  {
    id: 63,
    topic: "scrumGuide",
    prompt: "Choose the correct order for the pillars of the Waterfall Methodology.",
    options: [
      "Design, code, requirements gathering, delivery, testing",
      "Requirements gathering, code, testing, design, delivery",
      "Requirements gathering, design, code, testing, delivery",
      "Design, requirements gathering, code, testing, delivery",
      "Design, backlogging, code, testing, reevaluate, delivery",
    ],
    correctAnswer: "Requirements gathering, design, code, testing, delivery",
    explanation: "The waterfall model follows a linear sequence starting with requirements, then design, implementation (code), testing, and finally delivery.",
  },
  {
    id: 64,
    topic: "scrumEvents",
    prompt: "Which is not part of a weekly schedule for a scrum team?",
    options: [
      "Planning",
      "Daily Stand-up",
      "Story Time",
      "Dedicated testing day",
      "Retrospective",
    ],
    correctAnswer: "Dedicated testing day",
    explanation: "Testing is integrated continuously throughout the sprint in Scrum, not assigned to a separate dedicated day.",
  },
  {
    id: 65,
    topic: "scrumGuide",
    prompt: "What is the primary measure of progress in agile development?",
    options: [
      "Working software",
      "Team cohesion",
      "Profit",
      "Number of meetings",
      "Happiness",
    ],
    correctAnswer: "Working software",
    explanation: "Agile defines progress based on delivering functional, working software rather than metrics like meetings or documentation.",
  },
  {
    id: 66,
    topic: "scrumArtifacts",
    prompt: "What is the product backlog?",
    options: [
      "A list of desired features for the product",
      "A list of bugs the developers found",
      "A list of features the developers don't know how to implement",
      "A list of products the company is working on",
      "A list of tools the developers need",
    ],
    correctAnswer: "A list of desired features for the product",
    explanation: "The product backlog is a prioritized list of features, enhancements, and requirements for the product.",
  },
  {
    id: 67,
    topic: "scrumGuide",
    prompt: "Which of the following is a goal of test driven development?",
    options: [
      "To make the code more efficient",
      "To decrease the time taken to write the code",
      "To help programmers be less lonely",
      "To save company resources",
      "To rapidly create code that is well-designed and verifiably correct",
    ],
    correctAnswer: "To rapidly create code that is well-designed and verifiably correct",
    explanation: "Test-driven development focuses on writing tests first to guide development, resulting in reliable, well-structured, and verifiable code.",
  },
  {
    id: 68,
    topic: "scrumGuide",
    prompt: "What is Ping-Pong Pairing?",
    options: [
      "Two people playing ping-pong together.",
      "Coding a failing test, passing test, and refactoring by yourself.",
      "A game where two people pass the keyboard back and forth, writing a failing test, writing a passing test, and performing a refactoring together.",
      "Where a player is paired with a ping pong paddle.",
      "None of the above.",
    ],
    correctAnswer: "A game where two people pass the keyboard back and forth, writing a failing test, writing a passing test, and performing a refactoring together. ",
    explanation: "Ping-pong pairing is a collaborative technique where developers alternate writing tests and code, working together in a structured cycle.",
  },
  {
    id: 69,
    topic: "scrumRoles",
    prompt: "Which of the following is NOT a role of the Product Owner?",
    options: [
      "Holds the vision for the product",
      "Represents the business",
      "Owns the product backlog",
      "Prioritizes stories",
      "Develops user stories",
    ],
    correctAnswer: "Develops user stories",
    explanation: "While the Product Owner manages and prioritizes user stories, the team typically collaborates in creating and refining them.",
  },
  {
    id: 70,
    topic: "scrumGuide",
    prompt: "What is the one common value shared by all Agile processes?",
    options: [
      "Work as efficiently as possible",
      "The waterfall model is an obsolete business model",
      "Embrace change, rather than seeing it as an obstacle",
      "Software developers are of higher priority than anyone else",
      "Different steps of workflow must be followed to ensure punctuality",
    ],
    correctAnswer: "Embrace change, rather than seeing it as an obstacle",
    explanation: "Agile methodologies emphasize adaptability and responsiveness, viewing change as an opportunity to improve the product.",
  },
  {
    id: 71,
    topic: "scrumGuide",
    prompt: "When do you use Fibonacci numbers in Scrum?",
    options: [
      "When determining how many sprints you will do.",
      "When estimating how long a story will take.",
      "When planning the number of teammates you will need.",
      "When determining how many tasks you need to do vs how many you've done.",
      "When giving the product owner a price estimate.",
    ],
    correctAnswer: "When estimating how long a story will take.",
    explanation: "Fibonacci numbers are commonly used in story point estimation because their increasing gaps help teams better distinguish relative effort.",
  },
  {
    id: 72,
    topic: "scrumGuide",
    prompt: "What is refactoring?",
    options: [
      "Changing user stories based on new client requirements",
      "Rewriting code to make it easier to maintain, while keeping the same functionality.",
      "Changing Scrum roles based on developer strengths.",
      "Programming with TDD (test driven development).",
      "Restarting a Sprint cycle.",
    ],
    correctAnswer: "Rewriting code to make it easier to maintain, while keeping the same functionality.",
    explanation: "Refactoring improves the internal structure of code without changing its external behavior, making it easier to maintain and extend.",
  },
  {
    id: 73,
    topic: "scrumEvents",
    prompt: "On average how long should a sprint last?",
    options: [
      "1-4 days",
      "The whole project",
      "1-4 weeks",
      "5-10 weeks",
      "4-8 hours",
    ],
    correctAnswer: "1-4 weeks",
    explanation: "Sprints are time-boxed iterations typically lasting between one and four weeks to maintain focus and allow for regular feedback.",
  },
  {
    id: 74,
    topic: "scrumGuide",
    prompt: "Which resource is usually varied in an agile approach?",
    options: [
      "Scope",
      "Cost",
      "Time",
      "Quality",
      "None of these",
    ],
    correctAnswer: "Scope",
    explanation: "In agile, time and cost are usually fixed, while scope is adjusted to ensure the most valuable features are delivered.",
  },
  {
    id: 75,
    topic: "scrumGuide",
    prompt: "What pattern is commonly used to estimate story sizes?",
    options: [
      "Powers of 2",
      "Pentagonal number series",
      "Catalan number series",
      "There is no pattern",
      "Fibonacci series",
    ],
    correctAnswer: "Fibonacci series",
    explanation: "The Fibonacci sequence is commonly used in estimation because it reflects increasing uncertainty as work size grows.",
  },
  {
    id: 76,
    topic: "scrumGuide",
    prompt: "Which of the following terms describes the rate at which story points are completed?",
    options: [
      "Velocity",
      "Story cost",
      "Point speed",
      "Tempo",
      "Momentum",
    ],
    correctAnswer: "Velocity",
    explanation: "Velocity measures how many story points a team completes during a sprint and helps with planning future work.",
  },
  {
    id: 77,
    topic: "scrumEvents",
    prompt: "What marks the beginning of a sprint?",
    options: [
      "Sprint planning",
      "Story time",
      "Sprint demo",
      "Retrospective",
      "Stand-up",
    ],
    correctAnswer: "Sprint planning",
    explanation: "A sprint begins with sprint planning, where the team decides what work will be completed and how it will be accomplished.",
  },
  {
    id: 78,
    topic: "scrumEvents",
    prompt: "What is something you don't do in during daily scrums?",
    options: [
      "Talk about what you did yesterday",
      "Talk about what you're going to do today",
      "Meet daily briefly",
      "Talk about possible obstacles that might slow you down",
      "Talk about how your co-workers are slacking off",
    ],
    correctAnswer: "Talk about how your co-workers are slacking off",
    explanation: "Daily scrums are meant for brief updates on progress and blockers, not for criticizing teammates or discussing personal performance issues.",
  },
  {
    id: 79,
    topic: "scrumArtifacts",
    prompt: "What is the 'definition of done'?",
    options: [
      "When a feature has been completely coded",
      "When a feature has passed a performance test",
      "A definition that must include code review, design review, refactoring, and performance testing.",
      "Acceptance criteria",
      "An arbitrary definition unique to your team and your project",
    ],
    correctAnswer: "An arbitrary definition unique to your team and your project",
    explanation: "The definition of done is a shared agreement within the team that defines when work is considered complete, and it can vary by team and project.",
  },
  {
    id: 80,
    topic: "scrumGuide",
    prompt: "Which of the following does not describe paper prototyping?",
    options: [
      "It removes technological barriers",
      "It encourages participation in the design process",
      "It is not a part of scrum, but intrinsically agile",
      "It includes rapid feedback cycles",
      "It has to be facilitated by professionals",
    ],
    correctAnswer: "It has to be facilitated by professionals ",
    explanation: "Paper prototyping is simple and accessible, allowing anyone to participate without requiring professional facilitation.",
  },
  {
    id: 81,
    topic: "scrumRoles",
    prompt: "What is the NOT the role of the Scrum Master?",
    options: [
      "Helps the team get the most value out of scrum",
      "To assume authority over others",
      "To act as a coach",
      "To organize the team",
      "To be a scrum expert",
    ],
    correctAnswer: "To assume authority over others",
    explanation: "The Scrum Master is a servant-leader who supports the team, not someone who holds authority or manages others.",
  },
  {
    id: 82,
    topic: "scrumRoles",
    prompt: "Which of the following is NOT the role of a product owner?",
    options: [
      "Represents the customers.",
      "Prioritizes the items in the product backlog. ",
      "Constantly pushes team members to meet a deadline.",
      "Is available to answer team members' questions.",
      "Creates acceptance criteria for the back log items.",
    ],
    correctAnswer: "Constantly pushes team members to meet a deadline.",
    explanation: "The Product Owner focuses on maximizing value and prioritization, not pressuring the team or managing deadlines directly.",
  },
  {
    id: 83,
    topic: "scrumGuide",
    prompt: "Which is not one of the Agile Principles?",
    options: [
      "The highest priority is to satisfy the customer through early and continuous delivery of valuable software",
      "Business people and developers must work together daily throughout the project",
      "Working software is the primary measure of progress",
      "Continuous attention to technical excellence and good design enhances quality",
      "Only when problems arise, the team reflects on how to become more effective, then adjusts its behavior accordingly",
    ],
    correctAnswer: "Only when problems arise, the team reflects on how to become more effective, then adjusts its behavior accordingly",
    explanation: "Agile promotes continuous reflection and improvement, not only reacting when problems occur.",
  },
  {
    id: 84,
    topic: "scrumGuide",
    prompt: "What are the Agile Values?",
    options: [
      "Individuals and interactions over processes and tools",
      "Working software over comprehensive documentation.",
      "Customer collaboration over contract negotiation.",
      "Responding to change over following a plan.",
      "All of the other options",
    ],
    correctAnswer: "All of the other options",
    explanation: "All listed options are part of the Agile Manifesto, which defines the core values of agile development.",
  },
  {
    id: 85,
    topic: "scrumArtifacts",
    prompt: "The sprint backlog is:",
    options: [
      "A list of grievances the team performed during the sprint",
      "A journal for the scrum master to record personal notes",
      "A list of the members working on this sprint",
      "The team's to do list for the sprint",
      "A list of investors for this project",
    ],
    correctAnswer: "The team's to do list for the sprint",
    explanation: "The sprint backlog contains the tasks and work the team commits to completing during the sprint.",
  },
  {
    id: 86,
    topic: "scrumGuide",
    prompt: "What is paper prototyping used for?",
    options: [
      "To-do lists",
      "Planning UI/UX",
      "Developing the micro-charter",
      "Developing the plan for the software features",
      "Figuring out trade-offs",
    ],
    correctAnswer: "Planning UI/UX",
    explanation: "Paper prototyping is used to quickly design and test user interfaces before building them in code.",
  },
  {
    id: 87,
    topic: "scrumRoles",
    prompt: "What are the responsibilities of a product owner?",
    options: [
      "Engage with the customer to give feasibility and a line of communication throughout the development cycle.",
      "Assign the roles of each team member in what they should be working on throughout the week.",
      "Be the manager for the team.",
      "Write the test cases and make sure the product is working well.",
      "Be a helper in assigning the tasks of each team member.",
    ],
    correctAnswer: "Engage with the customer to give feasibility and a line of communication throughout the development cycle.",
    explanation: "The Product Owner represents stakeholders and ensures clear communication and alignment between the team and the customer.",
  },
  {
    id: 88,
    topic: "scrumArtifacts",
    prompt: "The list of tasks identified by a scrum team to be completed for a sprint is the:",
    options: [
      "Sprint backlog",
      "Project manager's playbook",
      "Code's comments",
      "Burn up chart",
      "Task board",
    ],
    correctAnswer: "Sprint backlog",
    explanation: "The sprint backlog is the set of tasks the team plans to complete during a specific sprint.",
  },
  {
    id: 89,
    topic: "scrumArtifacts",
    prompt: "What is the definition of done?",
    options: [
      "When the programmer thinks he finished his part",
      "When code review is finished",
      "When the documentation is finished",
      "When performance testing is finished",
      "When team members achieved something that is defined as the beginning of the project as the definition of done",
    ],
    correctAnswer: "When team members achieved something that is defined as the beginning of the project as the definition of done",
    explanation: "The definition of done is a shared agreement that defines when work is complete based on criteria established at the start of the project.",
  },
  {
    id: 90,
    topic: "scrumRoles",
    prompt: "Which is a Scrum role?",
    options: [
      "Product Owner",
      "Scrum Owner",
      "Project Owner",
      "Project Manager",
      "Product Manager",
    ],
    correctAnswer: "Product Owner",
    explanation: "The Product Owner is one of the three defined Scrum roles, along with the Scrum Master and Developers.",
  },
  {
    id: 91,
    topic: "scrumRoles",
    prompt: "The optimal range for number of team members is:",
    options: [
      "5 to 9",
      "Less than 5",
      "5 per scrum master on the team",
      "Variable: Scaled to the size of the project",
      "1 per story, for the amount of stories that should be completed in an average sprint",
    ],
    correctAnswer: "5 to 9",
    explanation: "A Scrum team is typically 5 to 9 members to balance collaboration efficiency with sufficient skill coverage.",
  },
  {
    id: 92,
    topic: "scrumRoles",
    prompt: "Which of the following is the role of a team member?",
    options: [
      "Responsible for completing user stories to incrementally increase the value of the product.",
      "Represents the customers.",
      "Works as a facilitator.",
      "Owns the product backlog.",
      "Coaches the team members.",
    ],
    correctAnswer: "Responsible for completing user stories to incrementally increase the value of the product.",
    explanation: "Team members (developers) are responsible for delivering increments of working software by completing user stories.",
  },
  {
    id: 93,
    topic: "scrumRoles",
    prompt: "Which is NOT a responsibility for the product owner?",
    options: [
      "Understand and deliver what the customer needs to the rest of the team",
      "Must have knowledge in programming language(s)",
      "Prioritize tasks that needs to be done by the team",
      "Provides vision of the final product",
      "Answer questions that other team members have about the project",
    ],
    correctAnswer: "Must have knowledge in programming language(s)",
    explanation: "The Product Owner focuses on value, prioritization, and communication, not technical implementation or programming expertise.",
  },
  {
    id: 94,
    topic: "scrumRoles",
    prompt: "What is NOT the role of the Product Owner?",
    options: [
      "Holds the vision for the product",
      "Represents the business",
      "Represents the customer",
      "Owns the product backlog",
      "Is a coding member of the team",
    ],
    correctAnswer: "Is a coding member of the team",
    explanation: "The Product Owner defines and prioritizes work but is not responsible for coding or development tasks.",
  },
  {
    id: 95,
    topic: "scrumEvents",
    prompt: "Why do Sims and Johnson (the authors) recommend that you stand during morning briefings?",
    options: [
      "Standing helps the brain increase efficiency.",
      "Standing encourages team members to speak concisely, reducing time spent in a meeting.",
      "Standing helps the Scrum Master organize everyone.",
      "Programmers spend much of their time sitting at desks, therefore standing helps them stay healthy.",
      "Standing differentiates the product master and scrum master from the developers.",
    ],
    correctAnswer: "Standing encourages team members to speak concisely, reducing time spent in a meeting.",
    explanation: "Standing helps keep meetings short and focused, encouraging participants to communicate efficiently.",
  },
  {
    id: 96,
    topic: "scrumArtifacts",
    prompt: "How does the product backlog differ from the sprint backlog?",
    options: [
      "They do not differ",
      "Product backlog: cumulative list of desired deliverables for the product, sprint backlog: the team's to-do list for the sprint",
      "Product backlog: cumulative list of to-do items for the current sprint, sprint backlog: discarded tasks from previous sprints",
      "The product backlog cannot be modified but the sprint backlog can",
      "None of these answers are correct",
    ],
    correctAnswer: "Product backlog: cumulative list of desired deliverables for the product, sprint backlog: the team's to-do list for the sprint",
    explanation: "The product backlog contains all desired work for the product, while the sprint backlog contains the specific tasks selected for the current sprint.",
  },
  {
    id: 97,
    topic: "scrumRoles",
    prompt: "Which are the different scrum roles?",
    options: [
      "Architect, business analyst, designer, software developer, tester, documentation specialist",
      "Scrum master, product owner, team member",
      "Manager, supervisor, employees",
      "Scrum expert, coach, impediment bulldozer, facilitator",
      "Project manager, team coordinator, developer",
    ],
    correctAnswer: "Scrum master, product owner, team member",
    explanation: "Scrum defines three roles: Product Owner, Scrum Master, and Developers (team members).",
  },
  {
    id: 98,
    topic: "scrumEvents",
    prompt: "Which of the following best describes the daily scrum?",
    options: [
      "It is called the daily stand up because it is a short break where the team is encouraged to relax",
      "It is also called the daily stand up because meetings are short and the team sometimes remains standing to encourage brevity",
      "It is also called the daily stand up because it encourages people to stay active",
      "It is also called the daily stand up because there is a role reversal, where the listeners are standing and the person speaking remains seated",
      "It is also called the daily stand up because it is a detailed, long meeting that encourages people to voice their concerns, and intense discussions generally follow",
    ],
    correctAnswer: "It is also called the daily stand up because meetings are short and the team sometimes remains standing to encourage brevity ",
    explanation: "The daily scrum is a short, focused meeting where standing helps keep discussions brief and efficient.",
  },
  {
    id: 99,
    topic: "scrumEvents",
    prompt: "Which is a characteristic of the Daily Scrum?",
    options: [
      "Daily",
      "Small",
      "Brief",
      "Pointed",
      "All of the other options",
    ],
    correctAnswer: "All of the other options",
    explanation: "Daily scrums are short, focused, and occur every day, making all listed characteristics accurate.",
  },
  {
    id: 100,
    topic: "scrumArtifacts",
    prompt: "What is the sprint backlog?",
    options: [
      "Cumulative list of desired tasks to do",
      "To-do list for a sprint",
      "Features thought of during a sprint",
      "Tasks not completed during a sprint",
      "List of features the customer wants",
    ],
    correctAnswer: "To-do list for a sprint",
    explanation: "The sprint backlog is the set of tasks the team commits to completing during a specific sprint.",
  },
];
