export type ScrumQuestion = {
  id: number;
  prompt: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
};

export const scrumQuestions: ScrumQuestion[] = [
  {
    id: 1,
    prompt: "Who decides which stories to prioritize?",
    options: [
      "Scrum Master",
      "Investors",
      "Team Members",
      "Case Manager",
      "Product Owner",
    ],
    correctAnswer: "Product Owner",
  },
  {
    id: 2,
    prompt: "When should the team have retrospective meetings?",
    options: [
      "Every evening via conference call",
      "Three times per week during lunch",
      "At the end of each sprint",
      "Every morning before the workday starts",
      "Once before the release",
    ],
    correctAnswer: "At the end of each sprint",
  },
  {
    id: 3,
    prompt: "What is the benefit of the waterfall model?",
    options: [
      "Improves ROI",
      "Increases visibility",
      "Makes it easier to find defects earlier",
      "Accomodates changes easily",
      "It is a very disciplined approach",
    ],
    correctAnswer: "It is a very disciplined approach",
  },
  {
    id: 4,
    prompt: "Which of the following is not a scrum ceremony?",
    options: [
      "Daily scrum meeting",
      "Sprint retrospective",
      "Sprint review",
      "Sprint backlog",
      "Sprint planning",
    ],
    correctAnswer: "Sprint backlog",
  },
  {
    id: 5,
    prompt: "Which of the following help indicate what is left to do, what is in progress, and what is done?",
    options: [
      "The sprint backlog",
      "Burn charts",
      "Sprint retrospective",
      "Information radiators",
      "TPS reports",
    ],
    correctAnswer: "Information radiators",
  },
  {
    id: 6,
    prompt: "Which of the following is not a scrum artifact?",
    options: [
      "Information radiator",
      "Bug history",
      "Product backlog",
      "Definition of done",
      "Sprint backlog",
    ],
    correctAnswer: "Bug history",
  },
  {
    id: 7,
    prompt: "Which of the following is not in the micro charter?",
    options: [
      "Mission statement",
      "Ethical values",
      "Trade-offs",
      "Elevator pitch",
      "Risks",
    ],
    correctAnswer: "Ethical values",
  },
  {
    id: 8,
    prompt: "What does a burn down chart predict?",
    options: [
      "A rank of most productive team members from best to worst",
      "A list of features to be implemented in order of priority",
      "Work left to be done over time",
      "Amount of budget spent over time",
      "A list of use cases in order of priority",
    ],
    correctAnswer: "Work left to be done over time",
  },
  {
    id: 9,
    prompt: "What are the three scrum roles?",
    options: [
      "Product owner, scrum master, team member",
      "Product owner, scrum master, servant",
      "Product owner, manager, developer",
      "CEO, scrum master, team member",
      "CEO, manager, developer",
    ],
    correctAnswer: "Product owner, scrum master, team member",
  },
  {
    id: 10,
    prompt: "Which are bigger: tasks or stories?",
    options: [
      "You cannot tell becasue they are not time dependent",
      "It depends on the development status of the project",
      "Both are the same size",
      "Tasks",
      "Stories",
    ],
    correctAnswer: "Stories",
  },
  {
    id: 11,
    prompt: "What does the product owner do?",
    options: [
      "Controls the priority of backlog items",
      "Front-end programming",
      "Assigns tasks to the individual team members",
      "CSS and HTML programming",
      "Manages the publication of team reports",
    ],
    correctAnswer: "Controls the priority of backlog items",
  },
  {
    id: 12,
    prompt: "What is a sprint backlog?",
    options: [
      "What features the team wants to release",
      "What each team member brings to a sprint",
      "A wooden object you run on",
      "What the team needs to do for each sprint",
      "What features will be released in the product",
    ],
    correctAnswer: "What the team needs to do for each sprint",
  },
  {
    id: 13,
    prompt: "Which of the following is not a stage included in the waterfall method?",
    options: [
      "Coding",
      "Periodic meetings",
      "Design",
      "Testing",
      "Requirement gathering",
    ],
    correctAnswer: "Periodic meetings",
  },
  {
    id: 14,
    prompt: "Which is not a responsibility of the product owner?",
    options: [
      "Helps set the direction of the product",
      "Judges the work done",
      "Captures product vision",
      "Writes customer-centric items",
      "Creates initial product backlog",
    ],
    correctAnswer: "Judges the work done",
  },
  {
    id: 15,
    prompt: "What is not a characteristic of agile approaches?",
    options: [
      "Big design up front",
      "Small iterative cycles",
      "Fail-early lifecycle",
      "Provide early milestones",
      "Adaptive, empirical process",
    ],
    correctAnswer: "Big design up front",
  },
  {
    id: 16,
    prompt: "If a team's velocity is good, and they seem to be getting all work done by deadlines, what is an appropriate action?",
    options: [
      "Decrease the number of points per sprint",
      "Increase the number of points per sprint to get more work done",
      "Assign harder stories in the next sprint",
      "Decrease the size of the team",
      "Leave the number of points per sprint as is",
    ],
    correctAnswer: "Leave the number of points per sprint as is",
  },
  {
    id: 17,
    prompt: "Where does the name scrum come from?",
    options: [
      "It's an acronym for Software Coding and Reading Uniform Management",
      "From the action of scrubbing, figuratively polishing the inefficiency of software development",
      "It's a rugby term",
      "It's an acronym for Simple Code Refactoring Unique Methodology",
      "Its creator liked the way it sounded",
    ],
    correctAnswer: "It's a rugby term",
  },
  {
    id: 18,
    prompt: "Which of the following is not a feature of agile methodologies?",
    options: [
      "Perfect the requirements before you code",
      "Build cross-functional teams",
      "Deliver products early and often",
      "Test as you go",
      "Document as you go",
    ],
    correctAnswer: "Perfect the requirements before you code",
  },
  {
    id: 19,
    prompt: "Which of these are three common ways to estimate tasks for sprint planning?",
    options: [
      "Task wages, task meetings, task complexity",
      "Task hours, task points, task count",
      "Task drivers, task risks, task profit",
      "Task break-even, task weeks, task subtasks",
      "Task score, task variance, task years",
    ],
    correctAnswer: "Task hours, task points, task count",
  },
  {
    id: 20,
    prompt: "Which is not a role of the scrum master?",
    options: [
      "Team coach",
      "Helps understand the use of the artifacts of scrum",
      "Facilitates scrum meetings",
      "Team boss",
      "Removes impediments for the team",
    ],
    correctAnswer: "Team boss",
  },
  {
    id: 21,
    prompt: "Which are the three formal feedback cycles?",
    options: [
      "Paper prototyping, Q+A, story mapping",
      "User stories, daily scrum, sprint review",
      "Daily scrum, sprint review, retrospective",
      "Refactoring, testing, retrospective",
      "Q+A, testing, burn charts",
    ],
    correctAnswer: "Daily scrum, sprint review, retrospective",
  },
  {
    id: 22,
    prompt: "What is the first step of the waterfall method?",
    options: [
      "Gathering a team",
      "Designing the project",
      "Setting the stage",
      "Deciding what to do",
      "Requirements gathering",
    ],
    correctAnswer: "Requirements gathering",
  },
  {
    id: 23,
    prompt: "BDUF stands for what?",
    options: [
      "Best Decision Unit Features",
      "Big Design Unit File",
      "Big Design Up Front",
      "Biosoftware Development Utility Fact",
      "Bold Development Up Front",
    ],
    correctAnswer: "Big Design Up Front",
  },
  {
    id: 24,
    prompt: "What do all agile methods have in common?",
    options: [
      "Return methodologies",
      "Cross-functional methodologies",
      "Well-defined methodologies",
      "Iterative methodologies",
      "Bi-lateral methodologies",
    ],
    correctAnswer: "Iterative methodologies",
  },
  {
    id: 25,
    prompt: "Why do scrum meetings happen standing up?",
    options: [
      "To wake everyone up",
      "To encourage brevity",
      "To burn calories",
      "So it is uncomfortable for all involved",
      "So it can be done anywhere, also in the corridor",
    ],
    correctAnswer: "To encourage brevity",
  },
  {
    id: 26,
    prompt: "What is considered a good scrum team size?",
    options: [
      "7 +- 2",
      "3 +- 1",
      "15 +- 10",
      "9 +- 4",
      "5 +- 3",
    ],
    correctAnswer: "7 +- 2",
  },
  {
    id: 27,
    prompt: "Which is false about a story map?",
    options: [
      "It is always a replacement for a product backlog",
      "It indicates the priority of stories",
      "A story map was used to help write the book",
      "It helps the team understand how stories fit together",
      "It is two-dimensional",
    ],
    correctAnswer: "It is always a replacement for a product backlog",
  },
  {
    id: 28,
    prompt: "In TDD pair programming, what is the only move when in the red state?",
    options: [
      "Perform a refactoring",
      "Write code to make the failing tests pass",
      "Write new failing tests",
      "Redesign code from scratch",
      "Write new passing tests",
    ],
    correctAnswer: "Write code to make the failing tests pass",
  },
  {
    id: 29,
    prompt: "Which of these is a role in a scrum team?",
    options: [
      "Scrum apprentice",
      "Scrum analyzer",
      "Product overviewer",
      "Scrum master",
      "Product marketer",
    ],
    correctAnswer: "Scrum master",
  },
  {
    id: 30,
    prompt: "The scrum master roles include all the following except what?",
    options: [
      "Scrum expert and advisor",
      "Coach",
      "Prioritizes stories",
      "Impediment bulldozer",
      "Facilitator",
    ],
    correctAnswer: "Prioritizes stories",
  },
  {
    id: 31,
    prompt: "How long should sprints be?",
    options: [
      "1-4 months",
      "1-4 tasks",
      "1-4 days",
      "1-4 years",
      "1-4 weeks",
    ],
    correctAnswer: "1-4 weeks",
  },
  {
    id: 32,
    prompt: "The product backlog includes a list of what?",
    options: [
      "Preferred coding languages",
      "Features",
      "Available resources",
      "Client names",
      "Available funds",
    ],
    correctAnswer: "Features",
  },
  {
    id: 33,
    prompt: "The daily scrum is also called what?",
    options: [
      "Stand-up meeting",
      "Brief meeting",
      "Daily brainstorm",
      "Scrummy meeting",
      "Decision planning meeting",
    ],
    correctAnswer: "Stand-up meeting",
  },
  {
    id: 34,
    prompt: "What is refactoring?",
    options: [
      "Altering the internal structure of code without changing its external behavior",
      "Dividing a team up into smaller teams, or combining teams together",
      "A procedure that is done at the end of every sprint",
      "Replacing module with several smaller sub-modules",
      "Changing the priority of the features to be implemented in the product backlog",
    ],
    correctAnswer: "Altering the internal structure of code without changing its external behavior",
  },
  {
    id: 35,
    prompt: "Who is responsible for the product backlog?",
    options: [
      "Scrum master",
      "Project manager",
      "Product owner",
      "Team member",
      "Sprint backlogger",
    ],
    correctAnswer: "Product owner",
  },
  {
    id: 36,
    prompt: "What elements are in the iron triangle of a project?",
    options: [
      "Pace, integration, documentation",
      "Scope, deadline, knowledge",
      "Cost, documentation, integration",
      "Documentation, user requirements, API",
      "Speed, scope, cost",
    ],
    correctAnswer: "Speed, scope, cost",
  },
  {
    id: 37,
    prompt: "Scrum indicates an iterative approach to getting work done through what?",
    options: [
      "Leaps",
      "Loops",
      "Jumps",
      "Swims",
      "Sprints",
    ],
    correctAnswer: "Sprints",
  },
  {
    id: 38,
    prompt: "What shouldn't the daily scrum be?",
    options: [
      "Daily",
      "Optional",
      "Pointed",
      "Brief",
      "Small",
    ],
    correctAnswer: "Optional",
  },
  {
    id: 39,
    prompt: "The sprint backlog is what?",
    options: [
      "A review of what has been accomplished in previous sprints",
      "The team's to-do list for the sprint",
      "The list of all features to be included in the product",
      "The final sprint",
      "A large piece of wood that one wears while performing sprints",
    ],
    correctAnswer: "The team's to-do list for the sprint",
  },
  {
    id: 40,
    prompt: "When practicing agile methodologies, you will do all of the following except what?",
    options: [
      "Document as you go",
      "Design the full product first before all other stages",
      "Test as you go",
      "Build cross-functional teams",
      "Deliver product early and often",
    ],
    correctAnswer: "Design the full product first before all other stages",
  },
  {
    id: 41,
    prompt: "A backlog item is often to referred to as a what?",
    options: [
      "Quest",
      "Task",
      "Fable",
      "Chunk",
      "Story",
    ],
    correctAnswer: "Story",
  },
  {
    id: 42,
    prompt: "What is the correct order of the waterfall method?",
    options: [
      "Requirements, implementation, design, verification, maintenance",
      "Requirements, implementation, design, maintenance, verification",
      "Verification, design, requirements, maintenance, implementation",
      "Maintenance, verification, implementation, design, requirements",
      "Requirements, design, implementation, verification, maintenance",
    ],
    correctAnswer: "Requirements, design, implementation, verification, maintenance",
  },
  {
    id: 43,
    prompt: "What is the primary measure of progress in scrum?",
    options: [
      "ROI",
      "Number of meetings completed",
      "Accomplishment of team members' goals",
      "Completion of points in a contract",
      "Working software",
    ],
    correctAnswer: "Working software",
  },
  {
    id: 44,
    prompt: "How many scrum roles are there in a team?",
    options: [
      "4",
      "3",
      "6",
      "2",
      "5",
    ],
    correctAnswer: "3",
  },
  {
    id: 45,
    prompt: "What is not shared at the daily scrum?",
    options: [
      "What I plan to add for the next 3 scrums",
      "Quick points of development team members",
      "What I expect to accomplish by the next daily scrum",
      "What I accomplished since last daily scrum",
      "What obstacles are slowing me down",
    ],
    correctAnswer: "What I plan to add for the next 3 scrums",
  },
  {
    id: 46,
    prompt: "Which set of numbers correlate with the rate as humans easily perceive differences, and are thus useful for story point estimations?",
    options: [
      "Imaginary",
      "Primes",
      "Fibonacci",
      "Geometric",
      "Natural",
    ],
    correctAnswer: "Fibonacci",
  },
  {
    id: 47,
    prompt: "A task board is what type of radiator?",
    options: [
      "Importance",
      "Indispensable",
      "Inconsistency",
      "Information",
      "Inequality",
    ],
    correctAnswer: "Information",
  },
  {
    id: 48,
    prompt: "Which of the following is not part of the scrum development cycle?",
    options: [
      "Sprint retrospective",
      "Sprint planning",
      "Daily standup meeting",
      "Sprint refactoring",
      "Sprint review",
    ],
    correctAnswer: "Sprint refactoring",
  },
  {
    id: 49,
    prompt: "What is the point of estimating story size?",
    options: [
      "To decide which stories are worth adding to release backlog",
      "To provide predictability of schedule",
      "There is no point, assigning exact times is better",
      "To determine accountability for legal purpose",
      "To cut down planning so you can get to coding sooner",
    ],
    correctAnswer: "To provide predictability of schedule",
  },
  {
    id: 50,
    prompt: "Which is not a way of pair programming?",
    options: [
      "Divide and conquer pairing",
      "Driver-navigator pairing",
      "Ping-pong pairing",
      "TDD pair programming",
      "Test driven development pair programming",
    ],
    correctAnswer: "Divide and conquer pairing",
  },
];
